Improve the project README.md (#21)
* Improve the project README.md

* Add `all` status check

* Fix whitespace in ci.yml

* Remove docs job which doesn't exist

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -50,3 +50,20 @@ jobs:
     if: ${{ needs.changes.outputs.unit-tests == 'true' }}
     needs: [changes, style]
     uses: ./.github/workflows/unit-tests.yml
+
+  all:
+    needs:
+     - changes
+     - style
+     - unit-tests
+    if: always()
+    runs-on: ubuntu-latest
+    steps:
+    - name: Status summary
+      run: |
+        if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+          echo "One or more required jobs failed or were cancelled"
+          exit 1
+        else
+          echo "All jobs completed successfully"
+        fi
